on:
  pull_request:
    types: [synchronize]

defaults:
  run:
    working-directory: dagger

jobs:
  textlint-ja:
    name: lint documents
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3
      - name: go get
        run: go get -v
      - name: run dagger ci
        run: go run main.go
